package transfer

import (
	"bufio"
	"bytes"
	"context"
	"database/sql"
	"encoding/csv"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"
)

// ImportResult contains metrics on the completed data import.
type ImportResult struct {
	TableName    string        `json:"tableName"`
	RowsImported int           `json:"rowsImported"`
	Duration     time.Duration `json:"duration"`
	DurationMs   float64       `json:"durationMs"`
	Columns      []string      `json:"columns"`
	TableCreated bool          `json:"tableCreated"`
}

// GenerateSqlDump creates a complete SQL DDL and DML dump of the specified tables or the entire database.
func GenerateSqlDump(ctx context.Context, db *sql.DB, out io.Writer, tables []string) error {
	writer := bufio.NewWriter(out)
	defer writer.Flush()

	fmt.Fprintf(writer, "-- SQLite dump generated by LiteLens Studio at %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(writer, "PRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n\n")

	// Determine tables to dump
	var targetTables []string
	if len(tables) > 0 {
		targetTables = tables
	} else {
		rows, err := db.QueryContext(ctx, "SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name;")
		if err != nil {
			return fmt.Errorf("failed listing tables: %w", err)
		}
		defer rows.Close()
		for rows.Next() {
			var name string
			if err := rows.Scan(&name); err == nil {
				targetTables = append(targetTables, name)
			}
		}
	}

	for _, tbl := range targetTables {
		// 1. Get DDL
		var ddl string
		err := db.QueryRowContext(ctx, "SELECT sql FROM sqlite_schema WHERE type='table' AND name = ?;", tbl).Scan(&ddl)
		if err != nil {
			continue
		}
		fmt.Fprintf(writer, "-- Table: %s\nDROP TABLE IF EXISTS %s;\n%s;\n\n", quoteIdentifier(tbl), quoteIdentifier(tbl), ddl)

		// 2. Dump rows
		selectQuery := fmt.Sprintf("SELECT * FROM %s;", quoteIdentifier(tbl))
		rows, err := db.QueryContext(ctx, selectQuery)
		if err != nil {
			continue
		}

		cols, err := rows.Columns()
		if err != nil {
			rows.Close()
			continue
		}

		colList := make([]string, len(cols))
		for i, c := range cols {
			colList[i] = quoteIdentifier(c)
		}
		colsJoined := strings.Join(colList, ", ")

		count := 0
		for rows.Next() {
			count++
			vals := make([]any, len(cols))
			ptrs := make([]any, len(cols))
			for i := range vals {
				ptrs[i] = &vals[i]
			}
			if err := rows.Scan(ptrs...); err != nil {
				continue
			}

			valStrs := make([]string, len(cols))
			for i, v := range vals {
				valStrs[i] = formatSqlValue(v)
			}
			fmt.Fprintf(writer, "INSERT INTO %s (%s) VALUES (%s);\n", quoteIdentifier(tbl), colsJoined, strings.Join(valStrs, ", "))
		}
		rows.Close()

		if count > 0 {
			fmt.Fprintln(writer)
		}

		// 3. Dump indexes for this table
		idxRows, err := db.QueryContext(ctx, "SELECT sql FROM sqlite_schema WHERE type='index' AND tbl_name = ? AND sql IS NOT NULL;", tbl)
		if err == nil {
			for idxRows.Next() {
				var idxSql string
				if err := idxRows.Scan(&idxSql); err == nil {
					fmt.Fprintf(writer, "%s;\n", idxSql)
				}
			}
			idxRows.Close()
			fmt.Fprintln(writer)
		}
	}

	fmt.Fprintf(writer, "COMMIT;\n")
	return nil
}

// ExportCsv streams table rows formatted as standard CSV.
func ExportCsv(ctx context.Context, db *sql.DB, tableName string, out io.Writer) error {
	rows, err := db.QueryContext(ctx, fmt.Sprintf("SELECT * FROM %s;", quoteIdentifier(tableName)))
	if err != nil {
		return err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return err
	}

	csvWriter := csv.NewWriter(out)
	defer csvWriter.Flush()

	// Write header
	if err := csvWriter.Write(cols); err != nil {
		return err
	}

	record := make([]string, len(cols))
	vals := make([]any, len(cols))
	ptrs := make([]any, len(cols))
	for i := range vals {
		ptrs[i] = &vals[i]
	}

	for rows.Next() {
		if err := rows.Scan(ptrs...); err != nil {
			return err
		}
		for i, v := range vals {
			if v == nil {
				record[i] = ""
			} else {
				switch val := v.(type) {
				case []byte:
					record[i] = string(val)
				default:
					record[i] = fmt.Sprintf("%v", val)
				}
			}
		}
		if err := csvWriter.Write(record); err != nil {
			return err
		}
	}

	return rows.Err()
}

// ExportJsonl streams table rows formatted as newline-delimited JSON.
func ExportJsonl(ctx context.Context, db *sql.DB, tableName string, out io.Writer) error {
	rows, err := db.QueryContext(ctx, fmt.Sprintf("SELECT * FROM %s;", quoteIdentifier(tableName)))
	if err != nil {
		return err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return err
	}

	vals := make([]any, len(cols))
	ptrs := make([]any, len(cols))
	for i := range vals {
		ptrs[i] = &vals[i]
	}

	enc := json.NewEncoder(out)
	for rows.Next() {
		if err := rows.Scan(ptrs...); err != nil {
			return err
		}
		rowMap := make(map[string]any, len(cols))
		for i, col := range cols {
			val := vals[i]
			if b, ok := val.([]byte); ok {
				rowMap[col] = string(b)
			} else {
				rowMap[col] = val
			}
		}
		if err := enc.Encode(rowMap); err != nil {
			return err
		}
	}

	return rows.Err()
}

// ImportCsv parses CSV data, automatically creates table if requested, and batch-inserts rows.
func ImportCsv(ctx context.Context, db *sql.DB, tableName string, r io.Reader, createIfMissing bool) (*ImportResult, error) {
	start := time.Now()
	csvReader := csv.NewReader(r)

	headers, err := csvReader.Read()
	if err != nil {
		return nil, fmt.Errorf("failed reading CSV header: %w", err)
	}

	if len(headers) == 0 {
		return nil, fmt.Errorf("CSV has no columns")
	}

	// Read all rows
	allRecords, err := csvReader.ReadAll()
	if err != nil {
		return nil, fmt.Errorf("failed parsing CSV rows: %w", err)
	}

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	tableCreated := false
	if createIfMissing {
		// Infer column types
		colTypes := inferColumnTypes(headers, allRecords)
		var colDefs []string
		for i, h := range headers {
			colDefs = append(colDefs, fmt.Sprintf("%s %s", quoteIdentifier(h), colTypes[i]))
		}
		createSQL := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (%s);", quoteIdentifier(tableName), strings.Join(colDefs, ", "))
		if _, err := tx.ExecContext(ctx, createSQL); err != nil {
			return nil, fmt.Errorf("failed creating table: %w", err)
		}
		tableCreated = true
	}

	// Prepare batch insert
	colPlaceholders := make([]string, len(headers))
	quotedHeaders := make([]string, len(headers))
	for i, h := range headers {
		colPlaceholders[i] = "?"
		quotedHeaders[i] = quoteIdentifier(h)
	}
	insertSQL := fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s);",
		quoteIdentifier(tableName),
		strings.Join(quotedHeaders, ", "),
		strings.Join(colPlaceholders, ", "),
	)

	stmt, err := tx.PrepareContext(ctx, insertSQL)
	if err != nil {
		return nil, fmt.Errorf("failed preparing insert statement: %w", err)
	}
	defer stmt.Close()

	rowsImported := 0
	for _, record := range allRecords {
		args := make([]any, len(headers))
		for i := 0; i < len(headers); i++ {
			if i < len(record) {
				args[i] = parseInferredValue(record[i])
			} else {
				args[i] = nil
			}
		}
		if _, err := stmt.ExecContext(ctx, args...); err != nil {
			return nil, fmt.Errorf("row %d insertion failed: %w", rowsImported+1, err)
		}
		rowsImported++
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}

	dur := time.Since(start)
	return &ImportResult{
		TableName:    tableName,
		RowsImported: rowsImported,
		Duration:     dur,
		DurationMs:   float64(dur.Microseconds()) / 1000.0,
		Columns:      headers,
		TableCreated: tableCreated,
	}, nil
}

// ImportJson parses a JSON array or JSONL stream and inserts rows.
func ImportJson(ctx context.Context, db *sql.DB, tableName string, r io.Reader, createIfMissing bool) (*ImportResult, error) {
	start := time.Now()

	// Read all content to determine structure
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	data = bytes.TrimSpace(data)
	var records []map[string]any

	if len(data) > 0 && data[0] == '[' {
		// JSON Array
		if err := json.Unmarshal(data, &records); err != nil {
			return nil, fmt.Errorf("invalid JSON array: %w", err)
		}
	} else {
		// Try JSONL
		scanner := bufio.NewScanner(bytes.NewReader(data))
		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" {
				continue
			}
			var m map[string]any
			if err := json.Unmarshal([]byte(line), &m); err != nil {
				return nil, fmt.Errorf("invalid JSONL line: %w", err)
			}
			records = append(records, m)
		}
	}

	if len(records) == 0 {
		return nil, fmt.Errorf("no records found in JSON input")
	}

	// Extract unique columns
	colSet := make(map[string]bool)
	var columns []string
	for _, rec := range records {
		for k := range rec {
			if !colSet[k] {
				colSet[k] = true
				columns = append(columns, k)
			}
		}
	}

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	tableCreated := false
	if createIfMissing {
		var colDefs []string
		for _, col := range columns {
			colDefs = append(colDefs, fmt.Sprintf("%s TEXT", quoteIdentifier(col)))
		}
		createSQL := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (%s);", quoteIdentifier(tableName), strings.Join(colDefs, ", "))
		if _, err := tx.ExecContext(ctx, createSQL); err != nil {
			return nil, fmt.Errorf("failed creating table: %w", err)
		}
		tableCreated = true
	}

	quotedCols := make([]string, len(columns))
	placeholders := make([]string, len(columns))
	for i, c := range columns {
		quotedCols[i] = quoteIdentifier(c)
		placeholders[i] = "?"
	}

	insertSQL := fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s);",
		quoteIdentifier(tableName),
		strings.Join(quotedCols, ", "),
		strings.Join(placeholders, ", "),
	)

	stmt, err := tx.PrepareContext(ctx, insertSQL)
	if err != nil {
		return nil, fmt.Errorf("failed preparing insert: %w", err)
	}
	defer stmt.Close()

	rowsImported := 0
	for _, rec := range records {
		args := make([]any, len(columns))
		for i, c := range columns {
			val := rec[c]
			switch v := val.(type) {
			case map[string]any, []any:
				b, _ := json.Marshal(v)
				args[i] = string(b)
			default:
				args[i] = v
			}
		}
		if _, err := stmt.ExecContext(ctx, args...); err != nil {
			return nil, fmt.Errorf("row %d insert error: %w", rowsImported+1, err)
		}
		rowsImported++
	}

	if err := tx.Commit(); err != nil {
		return nil, err
	}

	dur := time.Since(start)
	return &ImportResult{
		TableName:    tableName,
		RowsImported: rowsImported,
		Duration:     dur,
		DurationMs:   float64(dur.Microseconds()) / 1000.0,
		Columns:      columns,
		TableCreated: tableCreated,
	}, nil
}

func quoteIdentifier(id string) string {
	return `"` + strings.ReplaceAll(id, `"`, `""`) + `"`
}

func formatSqlValue(val any) string {
	if val == nil {
		return "NULL"
	}
	switch v := val.(type) {
	case int64:
		return strconv.FormatInt(v, 10)
	case float64:
		return strconv.FormatFloat(v, 'g', -1, 64)
	case bool:
		if v {
			return "1"
		}
		return "0"
	case []byte:
		return fmt.Sprintf("X'%s'", hex.EncodeToString(v))
	case string:
		return "'" + strings.ReplaceAll(v, "'", "''") + "'"
	default:
		return "'" + strings.ReplaceAll(fmt.Sprintf("%v", v), "'", "''") + "'"
	}
}

func parseInferredValue(s string) any {
	if s == "" {
		return nil
	}
	if i, err := strconv.ParseInt(s, 10, 64); err == nil {
		return i
	}
	if f, err := strconv.ParseFloat(s, 64); err == nil {
		return f
	}
	return s
}

func inferColumnTypes(headers []string, records [][]string) []string {
	types := make([]string, len(headers))
	for i := range headers {
		types[i] = "INTEGER"
	}

	for _, rec := range records {
		for i, val := range rec {
			if i >= len(types) || val == "" {
				continue
			}
			if types[i] == "TEXT" {
				continue
			}
			if _, err := strconv.ParseInt(val, 10, 64); err == nil {
				continue
			}
			if _, err := strconv.ParseFloat(val, 64); err == nil {
				types[i] = "REAL"
				continue
			}
			types[i] = "TEXT"
		}
	}
	return types
}
